### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by ArtemkaKun** [exercism/vlang#52]
Thanks, good work! ❤️ 

Are you present on the official V discord? You can add yourself there and post about things like that, I found this gem and community is happy too.
@1ethanhansen

![Screenshot_2023-02-03-07-16-38-529_com discord](https://user-images.githubusercontent.com/36485221/216526760-66e3c78f-e330-4a45-9c76-b17cde467ed8.png)
![Screenshot_2023-02-03-07-16-47-969_com discord](https://user-images.githubusercontent.com/36485221/216526771-42f5bd85-4969-49a3-994a-c3a7ebcc98a7.png)
![Screenshot_2023-02-03-07-17-03-669_com discord](https://user-images.githubusercontent.com/36485221/216526779-edb504ed-9d8a-4ec2-b3df-ddd676ea9dcb.png)

**Comment by 1ethanhansen** [comment]
@ArtemkaKun you're very welcome! I don't have discord so I didn't see this. I'm really glad people are appreciating the track :)

Would you be willing to deliver a message to the discord for me? Anyone who wants to contribute to helping people learn V is more than welcome to come contribute here! If you don't know where to start I would be more than happy to help people walk through implementing their first exercise step-by-step. Also, since I see someone mentioned community mentoring, I'm doing that too! If people want to get mentoring on V, people seem to think I do a pretty good job (https://exercism.org/profiles/1ethanhansen/testimonials)

(same offer applies to you :wink:)

**Comment by ArtemkaKun** [comment]
Sure, I will deliver you message

**Comment by 1ethanhansen** [comment]
Thank you!
